<?php

namespace FlightsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FlightsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlightsRepository extends EntityRepository
{
    public function findByHref($href, $user)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT flight
            FROM FlightsBundle:Flights flight WHERE
            flight.href = :href AND flight.user = :user'
        )->setParameter('href', $href)->setParameter('user', $user);

        $flight = $query->getOneOrNullResult();

        return $flight;
    }
}
